name: CI deployment
on:
  push:
    branches: [ group--{{__GROUP__}}--profile--{{__NAME__}}--{{__MODE__}} ]
    tags-ignore:
      - '*'
  # pull_request:
  #   branches: [ develop ]
# https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
    actions: none
    checks: none
    contents: read
    deployments: none
    id-token: write
    issues: none
    packages: none
    pages: none
    pull-requests: none
    repository-projects: none
    security-events: none
    statuses: none
env:
  GROUP_NAME: "{{__GROUP__}}"
  PROFILE_NAME: "{{__NAME__}}"
  PROFILE_MODE: "{{__MODE__}}"
  ARTIFACTS_REPO: "group--{{__GROUP__}}--profile--{{__NAME__}}--{{__MODE__}}"
jobs:
  build:
#    if: "!contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-24.04
    steps:
    - run:  |-
        uname -a
        arch
        pwd
        ls -la
    - run: 'echo "GITHUB_RUN_NUMBER: ${{ github.run_number }}"'
    - run: 'echo "GITHUB_RUN_ID: ${{ github.run_id }}"'
    - run: 'echo "GITHUB_SHA: ${{ github.sha }}"'
    - run: 'echo "GROUP_NAME: $GROUP_NAME"'
    - run: 'echo "PROFILE_NAME: $PROFILE_NAME"'
    - run: 'echo "PROFILE_MODE: $PROFILE_MODE"'
    - run: 'echo "ARTIFACTS_REPO: $ARTIFACTS_REPO"'
    - name: Checkout this repo
      uses: actions/checkout@v5
      with:
        path: profile
    - name: Checkout edrlab/customization-profile
      uses: actions/checkout@v5
      with:
        repository: edrlab/customization-profile
        path: customization-profile-meta-repo
        ref: 39a26ef6c516a8adc3523e339d1b3ad07a4ea42c
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: build package
      run: |-
        set -xe
        PWD_=$PWD

        ls -la profile
        ls -la customization-profile-meta-repo
        ls -la customization-profile-meta-repo/packager

        mkdir release

        node --version && npm --version
        npm --global install npm@^11
        npm --version
        npm cache clean --force
        npm cache verify

        cd customization-profile-meta-repo/packager

        npm ci --foreground-scripts
        npm run build

        PUB_KEY="${{ secrets.{{__MODE__UPER__}}_PUBLIC_KEY }}" PRIVATE_KEY="${{ secrets.{{__MODE__UPER__}}_PRIVATE_KEY }}" npm run cli -- --signed=true $PWD_/profile $PWD_/release

        cd $PWD_
        ls -la release
    - name: save release name
      id: release-name
      run: |-
          set -x
          ls release
          file=$(ls release)
          echo "release-name=$file"
          dir=$(dirname "$file")
          base=$(basename "$file")
          name="${base%.*}"
          ext="${base##*.}"
          slug=$(echo "$name" \
            | iconv -t ascii//TRANSLIT \
            | tr '[:upper:]' '[:lower:]' \
            | sed -E 's/[^a-z0-9]+/-/g' \
            | sed -E 's/^-+|-+$//g')
          filename="$slug.$ext"
          echo "filename_slugified=$filename"
          echo "value=$filename" >> $GITHUB_OUTPUT
          mv "release/$file" "release/$filename"
          echo "==== ls:"
          ls release
    - run: 'echo "release-name.value=${{ steps.release-name.outputs.value }}"'
    - uses: 'google-github-actions/auth@v3'
      with:
        project_id: 'customization-profile'
        workload_identity_provider: 'projects/681102121093/locations/global/workloadIdentityPools/github-action-identity-pool/providers/github-actions-provider'
        service_account: 'github-actions-service-account@customization-profile.iam.gserviceaccount.com'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v3'
      with:
        version: '>= 363.0.0'
    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    - name: 'List artifact registry'
      run: 'gcloud artifacts repositories list'
    - run: 'gcloud config set artifacts/location europe-west1'
    - run: 'gcloud artifacts repositories describe $ARTIFACTS_REPO 2>&1 || gcloud artifacts repositories create $ARTIFACTS_REPO --repository-format="generic" && gcloud config set artifacts/repository $ARTIFACTS_REPO'
    - name: get manifest version
      id: version
      run:  |-
          sudo apt install -y jq
          CREATED=$(jq .created profile/manifest.json -r)
          MODIFIED=$(jq .modified profile/manifest.json -r)
          echo "CREATED=$CREATED"
          echo "MODIFIED=$MODIFIED"
          echo "value=${MODIFIED:-$CREATED}" | tr 'A-Z' 'a-z' >> $GITHUB_OUTPUT
    - run: 'echo "version ${{ steps.version.outputs.value }}"'
    - run:  |-
        gcloud artifacts generic upload \
        --source="release/${{ steps.release-name.outputs.value }}" \
        --package="custom-profile.thorium" \
        --version="${{ steps.version.outputs.value }}"
    - run: gcloud artifacts files list
