FROM ubuntu:24.04
COPY --from=denoland/deno:bin-2.5.6 /deno /usr/local/bin/deno
COPY --from=node:24 /usr/local/bin/node /usr/local/bin/node
COPY --from=node:24 /usr/local/bin/npm /usr/local/bin/npm
ENV PORT=3000
WORKDIR /app
COPY src src/
COPY package-deno.json package.json
COPY package-lock.json .
COPY tsconfig.json .
COPY third-party third-party/
COPY scripts scripts/
RUN deno install && deno run build
EXPOSE ${PORT}
CMD ["deno","serve","--allow-read","--allow-env","--allow-net","dist/index.js"]
