FROM node:24-alpine
ENV PORT 3000
WORKDIR /app
COPY src src/
COPY package.json .
COPY package-lock.json .
COPY tsconfig.json .
COPY third-party third-party/
COPY scripts scripts/
RUN npm install && npm run build
EXPOSE $PORT
CMD ["node", "dist/index.js"]
