FROM debian:stable
COPY --from=oven/bun:1 /usr/local/bin/bun /usr/local/bin/bun
COPY --from=node:24 /usr/local/bin/node /usr/local/bin/node
COPY --from=node:24 /usr/local/bin/npm /usr/local/bin/npm
ENV PORT=3000
ENV __GIT_PATH=/usr/bin/git
WORKDIR /app
COPY src src/
COPY package-bun.json package.json
COPY package-lock.json .
COPY tsconfig.json .
COPY third-party third-party/
COPY scripts scripts/
COPY entrypoint.sh /entrypoint.sh

RUN set -x; \
echo $CONTAINER_TIMEZONE && \
arch && \
uname && \
date && \
# https://forums.docker.com/t/hash-sum-mismatch-writing-more-data-as-expected/45940/2
# https://github.com/jenkinsci/docker/issues/543#issuecomment-2568210821
echo "Acquire::http::Pipeline-Depth 0;" >> /etc/apt/apt.conf.d/99fixbadproxy && \
echo "Acquire::http::No-Cache true;" >> /etc/apt/apt.conf.d/99fixbadproxy && \
echo "Acquire::BrokenProxy    true;" >> /etc/apt/apt.conf.d/99fixbadproxy && \
apt-get -y update && \
ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && \
echo $CONTAINER_TIMEZONE > /etc/timezone && \
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata git

RUN set -xe; \
which git && echo OK || echo KO; \
which bun && echo OK || echo KO; \
which node && echo OK || echo KO; \
bun install && bun run build:container; \
chmod +x /entrypoint.sh; 


EXPOSE ${PORT}
CMD ["/entrypoint.sh", "bun", "run", "dist/index.js"]

# failed and crash on git binary not found, same as deno!
# error: Git Clone Error=Error: Error: ENOENT: no such file or directory, posix_spawn '/usr/bin/git'
#     at spawn (unknown)
#     at spawn (node:child_process:669:35)
#     at spawn (node:child_process:14:39)
#     at <anonymous> (/app/node_modules/simple-git/dist/esm/index.js:1415:27)
#     at new Promise (native:1:11)
#     at gitResponse (/app/node_modules/simple-git/dist/esm/index.js:1395:20)
#     at gitResponse (/app/node_modules/simple-git/dist/esm/index.js:1384:31)
#     at attemptRemoteTask (/app/node_modules/simple-git/dist/esm/index.js:1323:32)
#     at attemptRemoteTask (/app/node_modules/simple-git/dist/esm/index.js:1316:37)
#     at attemptTask (/app/node_modules/simple-git/dist/esm/index.js:1302:88)
#       at <anonymous> (/app/dist/controller/profile.js:125:23)
#       at async dispatch (/app/node_modules/hono/dist/compose.js:22:23)
#       at async <anonymous> (/app/node_modules/hono/dist/validator/validator.js:81:18)
#       at async dispatch (/app/node_modules/hono/dist/compose.js:22:23)
#       at async logger2 (/app/node_modules/hono/dist/middleware/logger/index.js:38:11)
#       at async dispatch (/app/node_modules/hono/dist/compose.js:22:23)
#       at async <anonymous> (/app/node_modules/hono/dist/hono-base.js:201:31)

