FROM debian:stable
COPY --from=denoland/deno:bin-2.5.6 /deno /usr/bin/deno
COPY --from=node:24 /usr/local/bin/node /usr/bin/node
COPY --from=node:24 /usr/local/bin/npm /usr/bin/npm
ENV PORT=3000
ENV __GIT_PATH=/usr/bin/git
WORKDIR /app
COPY src src/
COPY package-deno.json package.json
COPY package-lock.json .
COPY tsconfig.json .
COPY third-party third-party/
COPY scripts scripts/
COPY entrypoint.sh /entrypoint.sh
COPY eslint.config.mjs .

RUN set -x; \
echo $CONTAINER_TIMEZONE && \
arch && \
uname && \
date && \
# https://forums.docker.com/t/hash-sum-mismatch-writing-more-data-as-expected/45940/2
# https://github.com/jenkinsci/docker/issues/543#issuecomment-2568210821
echo "Acquire::http::Pipeline-Depth 0;" >> /etc/apt/apt.conf.d/99fixbadproxy && \
echo "Acquire::http::No-Cache true;" >> /etc/apt/apt.conf.d/99fixbadproxy && \
echo "Acquire::BrokenProxy    true;" >> /etc/apt/apt.conf.d/99fixbadproxy && \
apt-get -y update && \
ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && \
echo $CONTAINER_TIMEZONE > /etc/timezone && \
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata git

RUN set -xe; \
which git && echo OK || echo KO; \
which deno && echo OK || echo KO; \
which node && echo OK || echo KO; \
deno install && deno run lint && deno run build:container; \
chmod +x /entrypoint.sh; 

EXPOSE ${PORT}
CMD ["/entrypoint.sh", "deno","run","--allow-read","--allow-env","--allow-net","--allow-sys","--allow-write","--allow-run","dist/index.js"]

# Failed and crash !?
# error: Uncaught Error: spawnSync /usr/bin/git ENOENT
#     at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:90:3)
#     at __node_internal_errnoException (ext:deno_node/internal/errors.ts:138:10)
#     at _createSpawnSyncError (ext:deno_node/internal/child_process.ts:699:17)
#     at new ChildProcess (ext:deno_node/internal/child_process.ts:288:13)
#     at spawn (node:child_process:124:10)
#     at file:///app/node_modules/.deno/simple-git@3.30.0/node_modules/simple-git/dist/esm/index.js:1415:27
#     at new Promise (<anonymous>)
#     at GitExecutorChain.gitResponse (file:///app/node_modules/.deno/simple-git@3.30.0/node_modules/simple-git/dist/esm/index.js:1395:16)
#     at GitExecutorChain.attemptRemoteTask (file:///app/node_modules/.deno/simple-git@3.30.0/node_modules/simple-git/dist/esm/index.js:1323:32)
#     at GitExecutorChain.attemptTask (file:///app/node_modules/.deno/simple-git@3.30.0/node_modules/simple-git/dist/esm/index.js:1302:88)